Update python_script.yml

diff --git a/.github/workflows/python_script.yml b/.github/workflows/python_script.yml
--- a/.github/workflows/python_script.yml
+++ b/.github/workflows/python_script.yml
@@ -8,27 +8,23 @@ on:
     - cron: '* * * * *'
 
 jobs:
-  check_and_cancel:
+  check_for_running_jobs:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Cancel Previous Runs
+    - name: Check for running jobs
       run: |
         # Find any runs in progress from the same workflow
         runs=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/runs | jq -r '.workflow_runs[] | select(.head_branch == "${{ github.ref }}" and (.status == "in_progress" or .status == "queued" or .status == "waiting")) | .id')
-
-        # Cancel any found runs
-        for run in $runs
-        do
-          echo "Cancelling run: $run"
-          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/runs/$run/cancel
-        done
-
+        
+        # If there are any running jobs, fail this job
+        if [[ -n "$runs" ]]; then
+          echo "There are running jobs. Exiting..."
+          exit 1
+        fi
 
   run-python-script:
-    needs: check_and_cancel
+    needs: check_for_running_jobs
     runs-on: ubuntu-latest
-
     steps:
     - name: Check out repository
       uses: actions/checkout@v2
